### ISSUE TITLE
Change the website title

### ISSUE THREAD

**Issue by DavidMarom** [DavidMarom/next-exp#5]
![Image](https://user-images.githubusercontent.com/12570530/246624085-fda9baeb-1123-4902-bc46-78c869a4f06b.png)

How the hell do you change this ?? :)

**Comment by YogeshJoshi10072000** [comment]
i think use <title></title> in every html page of your website

**Comment by Sky-De** [comment]
Add 
<Header>
<title>YOUR TITLE HERE</title>
</Header>
to _app.js
Then all pages load with same title which you added here, however if you want you can add same thing to any page component with thier own title

**Comment by DavidMarom** [comment]
Thanks, will try now

**Comment by DavidMarom** [comment]
It works, Thank you :)
